Repository optimizely/oui, pull requests merged in 2018-07, with the labels that each got.

#985 Fixes #984 - Add HelpPopover component to OUI
  CHANGELOG.md
  src/components/HelpPopover/HelpPopover.story.js
  src/components/HelpPopover/index.js
  src/components/HelpPopover/tests/__snapshots__/index.js.snap
  src/components/HelpPopover/tests/index.js
Labels: :robot: 1 hrs

#988 Remove SelectDropdown filter functionality, and revert Dropdown components to before PR #961
  CHANGELOG.md
  src/components/Dropdown/Dropdown.story.js
  src/components/Dropdown/DropdownContents/index.js
  src/components/Dropdown/DropdownContents/tests/index.js
  src/components/Dropdown/DropdownListItem/index.js
  src/components/Dropdown/index.js
  src/components/Dropdown/tests/__snapshots__/index.js.snap
  src/components/Dropdown/tests/index.js
  src/components/SelectDropdown/SelectDropdown.story.js
  src/components/SelectDropdown/index.js
  src/components/SelectDropdown/tests/index.js
Labels: :robot: 0.1 hrs

#992 Add Accordion Bar React Component
  src/components/Accordion/Accordion.story.js
  src/components/Accordion/index.js
  src/components/Accordion/index.scss
  src/components/Accordion/tests/__snapshots__/index.js.snap
  src/components/Accordion/tests/index.js
  src/main.js
Labels: :robot: 4 hrs

#1008 Prep for new release version 31.9.2
  CHANGELOG.md
  package.json
  storybook/iframe.html
  storybook/index.html
  storybook/static/manager.166c5b1853b247e362bc.bundle.js
  storybook/static/manager.44e46416426bbc29c498.bundle.js
  storybook/static/preview.1a3a9f232b083ab136a1.bundle.js
  storybook/static/preview.8e3fbaddd146c23860c1.bundle.js
Labels: :robot: 1 hrs

#1009 Updated CHANGELOG to reflect correct changes in versions
  CHANGELOG.md
Labels: :robot: 0.2 hrs

#1003 Add maxLength prop to Input and Textarea
  CHANGELOG.md
  src/components/Input/Input.story.js
  src/components/Input/index.js
  src/components/Input/tests/index.js
  src/components/Textarea/Textarea.story.js
  src/components/Textarea/index.js
  src/components/Textarea/tests/index.js
Labels: :robot: 4 hrs, :robot: 8 hrs

#1010 Tweaks to SelectDropdown and Poptip
  package.json
  src/components/Poptip/Poptip.story.js
  src/components/Poptip/index.js
  src/components/SelectDropdown/SelectDropdown.story.js
  src/components/SelectDropdown/index.js
  src/components/SelectDropdown/tests/index.js
Labels: :robot: 4 hrs, :robot: 8 hrs
