Repository optimizely/oui, pull requests merged in 2018-09, with the labels that each got.

#1033 Add Steps component
  src/components/Steps/README.md
  src/components/Steps/Steps.story.js
  src/components/Steps/index.js
  src/components/Steps/index.scss
  src/components/Steps/tests/index.js
Labels: :robot: 24 hrs, :robot: 4 hrs

#1037 Fix disclose table styling post rebrand
  CHANGELOG.md
  src/components/DiscloseTable/index.scss
Labels: :robot: 1 hrs

#1039 update Radio component's label prop to accept node
  CHANGELOG.md
  src/components/Radio/Radio.story.js
  src/components/Radio/index.js
Labels: :robot: 0.1 hrs

#1044 Remove package-lock.json and add to gitignore
  .gitignore
  .npmignore
  CHANGELOG.md
  package-lock.json
Labels: :robot: 0.1 hrs
