Repository optimizely/oui, pull requests merged in 2018-11, with the labels that each got.

#1080 Fix debounce mechanism in autocomplete
  package.json
  src/components/Autocomplete/Autocomplete.js
  src/components/Autocomplete/tests/index.js
  yarn.lock
Labels: :robot: 1 hrs

#1074 Drau/listgroup component
  CHANGELOG.md
  src/components/Badge/Badge.story.js
  src/components/Input/Input.story.js
  src/components/Input/example/index.js
  src/components/ListGroup/ListGroup.story.js
  src/components/ListGroup/README.md
  src/components/ListGroup/index.js
  src/components/ListGroup/index.scss
  src/components/ListGroup/tests/__snapshots__/index.js.snap
  src/components/ListGroup/tests/index.js
  src/components/ProgressBar/ProgressBar.story.js
  src/main.js
  src/oui/_oui-partials.scss
Labels: :robot: 4 hrs, :robot: 8 hrs

#1082 maintenance (Asset Upload): Sync /dist assets to s3://design.optimizely.com/oui
  .travis.yml
Labels: :robot: 0.1 hrs

#1086 Drau/listgroup padding
  CHANGELOG.md
  src/components/ListGroup/ListGroup.story.js
  src/components/ListGroup/index.js
  src/components/ListGroup/index.scss
  src/components/ListGroup/tests/__snapshots__/index.js.snap
Labels: :robot: 4 hrs, :robot: 8 hrs

#1087 Separate SASS colors & variables files
  CHANGELOG.md
  src/oui/_oui-variables.scss
  src/oui/oui.scss
  src/overrides/Color/index.scss
Labels: :robot: 0.2 hrs

#1061 feat(FilterPicker): Add FilterPicker Render Component
  CHANGELOG.md
  package.json
  src/components/ExampleComponent/tests/index.js
  src/components/FilterPicker/FilterPicker.js
  src/components/FilterPicker/FilterPicker.story.js
  src/components/FilterPicker/FilterPickerListItem/index.js
  src/components/FilterPicker/README.md
  src/components/FilterPicker/index.js
  src/components/FilterPicker/index.scss
  src/components/FilterPicker/tests/__snapshots__/index.js.snap
  src/components/FilterPicker/tests/index.js
  src/main.js
  src/oui/_oui-partials.scss
  src/utils/filter.js
  storybook/iframe.html
  storybook/index.html
  storybook/static/manager.080384b586cd2065cd0f.bundle.js
  storybook/static/manager.81984818eaa80a8cb907.bundle.js
  storybook/static/preview.6ec9b2cad902572a4252.bundle.js
  storybook/static/preview.d74b13b69e3f45be05e3.bundle.js
  yarn.lock
Labels: :robot: 0.2 hrs

#1088 DropdownBlockLinkSecondaryText: Fix alignment & sizing of warning icon
  src/components/Dropdown/Dropdown.story.js
  src/components/Dropdown/DropdownBlockLinkSecondaryText/index.js
Labels: :robot: 2 hrs
