Repository optimizely/oui, pull requests merged in 2018-10, with the labels that each got.

#1034 Added auto-focus to the Textarea
  CHANGELOG.md
  src/components/Textarea/Textarea.story.js
  src/components/Textarea/example/index.js
  src/components/Textarea/index.js
Labels: :robot: 24 hrs, :robot: 4 hrs

#1046 Change font weight 400 for tiny button
  CHANGELOG.md
  src/oui/_oui-variables.scss
Labels: :robot: 12 hrs, :robot: 4 hrs

#1048 webpack storybook should disable babelrc and use react es2015 presets
  .storybook/webpack.config.js
Labels: :robot: 12 hrs, :robot: 4 hrs

#987 Button-Link Crossovers
  CHANGELOG.md
  src/components/Button/Button.story.js
  src/components/Button/index.js
  src/components/Button/tests/__snapshots__/index.js.snap
  src/components/Button/tests/index.js
  src/components/CopyButton/tests/__snapshots__/index.js.snap
  src/components/EmptyDashboard/tests/__snapshots__/index.js.snap
  src/components/Link/Link.story.js
  src/components/Link/index.js
  src/components/Link/tests/__snapshots__/index.js.snap
  src/components/Link/tests/index.js
Labels: :robot: 0.2 hrs

#1051 Refine input error states
  CHANGELOG.md
  src/components/Input/Input.story.js
  src/oui/partials/elements/_form.scss
Labels: :robot: 12 hrs, :robot: 4 hrs

#1053 Send Travis CI alerts to #oui-alerts
  .travis.yml
  CHANGELOG.md
Labels: :robot: 2 hrs

#1052 Create Pagination component
  CHANGELOG.md
  src/components/Pagination/Pagination.js
  src/components/Pagination/Pagination.story.js
  src/components/Pagination/README.md
  src/components/Pagination/examples/index.js
  src/components/Pagination/index.js
  src/components/Pagination/tests/index.js
  src/main.js
  storybook/iframe.html
  storybook/index.html
  storybook/static/manager.2df41dfd1752e946af6d.bundle.js
  storybook/static/manager.894a18d1b55832661a5a.bundle.js
  storybook/static/preview.cb7a0a7402023cd29d22.bundle.js
  storybook/static/preview.f110878d32b3d717e4d4.bundle.js
Labels: :robot: 2 hrs

#1057 Update global border radius to 5
  .storybook/borderradius.story.js
  .storybook/config.js
  .storybook/overview.story.js
  CHANGELOG.md
  src/oui/_oui-variables.scss
  src/stories/icons-example.story.js
Labels: :robot: 4 hrs, :robot: 6 hrs

#1056 Add mousedown event handler to BlockList.Item
  CHANGELOG.md
  src/components/BlockList/Item/index.js
  src/components/BlockList/Item/tests/index.js
Labels: :robot: 1 hrs

#1054 Migrating Toolbar component from optimizely.git
  CHANGELOG.md
  src/components/Button/index.scss
  src/components/Toolbar/Toolbar.story.js
  src/components/Toolbar/index.js
  src/components/Toolbar/index.scss
  src/main.js
  src/oui/_oui-partials.scss
  src/oui/_oui-variables.scss
Labels: :robot: 24 hrs, :robot: 4 hrs

#1063 improve(docs): Pull in PropType descriptions and README text in Storybook Stories
  .storybook/borderradius.story.js
  .storybook/config.js
  .storybook/overview.story.js
  .storybook/webpack.config.js
  CHANGELOG.md
  CONTRIBUTING.md
  package.json
  src/components/ExampleComponent/ExampleComponent.js
  src/components/ExampleComponent/ExampleComponent.story.js
  src/components/ExampleComponent/README.md
  src/components/ExampleComponent/index.js
  src/components/ExampleComponent/index.scss
  src/components/ExampleComponent/tests/__snapshots__/index.js.snap
  src/components/ExampleComponent/tests/index.js
  src/components/Link/Link.story.js
  src/oui/_oui-partials.scss
  storybook/static/manager.1648f60d8ee2d0fa686a.bundle.js
  storybook/static/preview.af64dcbe74fe6ad73029.bundle.js
  yarn-error.log
  yarn.lock
Labels: :robot: 4 hrs

#1068 Migrate Dialog component to OUI
  CHANGELOG.md
  src/components/Dialog/Dialog.story.js
  src/components/Dialog/Fieldset/index.js
  src/components/Dialog/Footer/index.js
  src/components/Dialog/Title/index.js
  src/components/Dialog/Wrapper/index.js
  src/components/Dialog/index.js
  src/main.js
  src/oui/_oui-partials.scss
  src/oui/_oui-variables.scss
  src/oui/partials/components/_layout.scss
  src/oui/partials/layout/_reading-column.scss
Labels: :robot: 2 hrs

#1070 Add test section to blocklist item
  CHANGELOG.md
  src/components/BlockList/Item/index.js
Labels: :robot: 0.2 hrs

#1071 Updates to autocomplete
  CHANGELOG.md
  src/components/Autocomplete/Autocomplete.js
  src/components/Autocomplete/tests/index.js
Labels: :robot: 1 hrs

#1073 [Fe-900] Fix ES module build of OUI not transpiling JSX
  .babelrc
  .eslintignore
  .gitignore
  .npmignore
  CHANGELOG.md
  package.json
  src/components/EmptyDashboard/index.js
  src/main.js
  yarn-error.log
  yarn.lock
Labels: :robot: 4 hrs, :robot: 6 hrs

#1075 docs: update contributing guide to fully embrace yarn
  CONTRIBUTING.md
Labels: :robot: 1 hrs

#1076 Include src/ in package to enable external bundling
  .npmignore
  CHANGELOG.md
Labels: :robot: 1 hrs
