Repository optimizely/oui, pull requests merged in 2018-08, with the labels that each got.

#1013 Update Checkbox's label prop to accept node #1012
  CHANGELOG.md
  src/components/Checkbox/Checkbox.story.js
  src/components/Checkbox/index.js
Labels: :robot: 4 hrs, :robot: 6 hrs

#1015 Dropdown should render children when isOpen is true
  src/components/Dropdown/tests/__snapshots__/index.js.snap
  src/components/Dropdown/tests/index.js
  src/utils/recompose-utils.js
Labels: :robot: 4 hrs, :robot: 6 hrs

#1017 Add oui-rule selector to horizontal rule css #1016
  CHANGELOG.md
  src/oui/partials/elements/_horizontal-rules.scss
Labels: :robot: 2 hrs

#1019 Update change log for upcoming release
  CHANGELOG.md
Labels: :robot: 0.2 hrs

#1022 remove package-lock.json since yarn rules this repo
  CHANGELOG.md
  package-lock.json
Labels: :robot: 0.2 hrs

#1026 Add mousedown handler to Button component
  CHANGELOG.md
  src/components/Button/index.js
  src/components/Button/tests/index.js
  src/components/CopyButton/tests/__snapshots__/index.js.snap
  src/components/EmptyDashboard/tests/__snapshots__/index.js.snap
Labels: :robot: 4 hrs, :robot: 8 hrs
