Repository optimizely/oui, pull requests merged in 2019-04, with the labels that each got.

#1138 patch(SelectDropdown): Fixed a Crash when value is not the items list.
  src/components/SelectDropdown/index.js
Labels: :robot: 4 hrs, :robot: 6 hrs

#1139 (fix) Update highlight.js version in yarn.lock
  yarn.lock
Labels: :robot: 0.2 hrs

#1141 feat(input/label): Create option to properly link a label to an input
  CHANGELOG.md
  src/components/Input/Input.story.js
  src/components/Input/index.js
  src/components/Input/tests/index.js
  src/components/Label/index.js
  src/components/Label/tests/index.js
Labels: :robot: 1 hrs

#1142 fix(changelog): Remove Tags from changelog causing rendering issues
  CHANGELOG.md
Labels: :robot: 0.1 hrs

#1143 Drau/button story
  .storybook/tokens.story.js
  CHANGELOG.md
  src/components/Button/Button.story.js
Labels: :robot: 1 hrs

#1134 feat(dialog/sheet): Update Dialog to be small window, add Sheet component
  CHANGELOG.md
  src/components/CloseButton/index.js
  src/components/CloseButton/index.scss
  src/components/CloseButton/tests/index.js
  src/components/Dialog/Deprecated/Footer/index.js
  src/components/Dialog/Deprecated/Title/index.js
  src/components/Dialog/Deprecated/Wrapper/index.js
  src/components/Dialog/Dialog.story.js
  src/components/Dialog/index.js
  src/components/Dialog/index.scss
  src/components/Dialog/tests/index.js
  src/components/Prompt/Prompt.story.js
  src/components/Prompt/index.js
  src/components/Prompt/index.scss
  src/components/Sheet/Sheet.story.js
  src/components/Sheet/index.js
  src/components/Sheet/index.scss
  src/components/Sheet/tests/index.js
  src/main.js
  src/oui/_oui-partials.scss
  src/oui/_oui-variables.scss
  src/oui/partials/sass/_mixins.scss
Labels: :robot: 4 hrs, :robot: 8 hrs

#1145 [maintenance] update node to v10.15.3
  .nvmrc
  CHANGELOG.md
  package.json
Labels: :robot: 0.2 hrs

#1147 Drau/token id java script
  CHANGELOG.md
  src/tokens/forimport/_index.scss
  src/tokens/forimport/index.cjs.js
  src/tokens/forimport/index.es.js
  src/tokens/index.js
  src/tokens/src/color.json
Labels: :robot: 0.2 hrs

#1140 feat(date-picker): Add new component for Single and Range date pickers
  CHANGELOG.md
  package.json
  src/components/Button/index.scss
  src/components/DatePicker/CalendarNavButton.js
  src/components/DatePicker/DatePicker.js
  src/components/DatePicker/DatePicker.story.js
  src/components/DatePicker/DateRangePicker.js
  src/components/DatePicker/DateRangePicker.story.js
  src/components/DatePicker/constants.js
  src/components/DatePicker/fns.js
  src/components/DatePicker/index.scss
  src/components/DatePicker/overrides.scss
  src/components/DatePicker/tests/index.js
  src/oui/_oui-partials.scss
  src/oui/library/react-dates/20.1.0/_index.scss
  src/oui/oui.scss
  yarn.lock
Labels: :robot: 24 hrs, :robot: 4 hrs

#1149 [FE-950] Upgrade react-popper and fix breaking changes
  package.json
  src/components/Dropdown/index.js
  src/components/Dropdown/tests/__snapshots__/index.js.snap
  yarn.lock
Labels: :robot: 1 hrs
