Repository optimizely/oui, pull requests merged in 2019-03, with the labels that each got.

#1131 fix(steps): Switch Active and Complete styling
  CHANGELOG.md
  src/components/Steps/index.scss
Labels: :robot: 1 hrs

#1133 patch(Select): Fixed Select export by exporting it in src/main.js
  CHANGELOG.md
  src/main.js
Labels: :robot: 1 hrs

#1132 Update arrowsinline and dropdown
  CHANGELOG.md
  src/components/ArrowsInline/ArrowInline.story.js
  src/components/ArrowsInline/index.js
  src/components/Dropdown/Dropdown.story.js
  src/components/Dropdown/index.js
  src/components/Dropdown/tests/__snapshots__/index.js.snap
Labels: :robot: 24 hrs, :robot: 4 hrs

#1136 patch(Input): Fixed the isRequired prop on <Input> component which wasn't working as expected.
  CHANGELOG.md
  src/components/EditableInput/tests/index.js
  src/components/ExampleComponent/tests/__snapshots__/index.js.snap
  src/components/FilterPicker/tests/__snapshots__/index.js.snap
  src/components/Input/Input.story.js
  src/components/Input/index.js
  src/components/Input/tests/index.js
Labels: :robot: 4 hrs, :robot: 6 hrs
