Repository optimizely/oui, pull requests merged in 2019-01, with the labels that each got.

#1097 feat (TagsInput Component): Add Component to edit groups of Tags
  package.json
  src/components/Token/DismissButton/index.js
  src/components/Token/Token.story.js
  src/components/Token/index.js
  src/components/Token/index.scss
  src/components/TokensInput/TokensInput.story.js
  src/components/TokensInput/index.js
  src/components/TokensInput/tests/index.js
  src/oui/_oui-variables.scss
  yarn.lock
Labels: :robot: 0.2 hrs

#1100 patch(SelectDropdown): SelectDropdown gets disabled when the isDisabled prop is true
  CHANGELOG.md
  src/components/Dropdown/index.js
  src/components/SelectDropdown/SelectDropdown.story.js
  src/components/SelectDropdown/index.js
  src/components/SelectDropdown/tests/index.js
Labels: :robot: 4 hrs, :robot: 6 hrs

#1102 feat (<Input>): Add the step property to <Input>
  src/components/Input/index.js
  src/components/Input/tests/index.js
Labels: :robot: 0.2 hrs

#1103 [FE-801] allow numeric values for Input component
  CHANGELOG.md
  src/components/Input/index.js
Labels: :robot: 1 hrs

#1104 docs(FilterPicker): Update Storybook and docs
  CHANGELOG.md
  src/components/FilterPicker/FilterPicker.story.js
  src/components/FilterPicker/README.md
  storybook/iframe.html
  storybook/static/preview.1de4707bc2eaaa617772.bundle.js
  storybook/static/preview.713c02ae376557ed9aa5.bundle.js
Labels: :robot: 4 hrs, :robot: 6 hrs
