Repository optimizely/oui, pull requests merged in 2019-12, with the labels that each got.

#1259 Migrate Legacy CSS from Optly.git to OUI
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  src/components/Table/index.scss
  src/oui/oui.scss
  src/oui/partials/sass/_mixins.scss
  src/oui/partials/sass/mixins/_keyframes.scss
  src/oui/partials/sass/mixins/_lists.scss
  src/oui/partials/sass/mixins/_math.scss
  src/oui/partials/sass/mixins/_no-select.scss
  src/oui/partials/sass/mixins/_utilities.scss
  src/overrides/Border/index.scss
Labels: :robot: 4 hrs, :robot: 6 hrs

#1257 fix(Container/Row/Col): Style updates for flexing
  .storybook/AppFrame.story.js
  CHANGELOG.md
  src/components/Layout/Col.js
  src/components/Layout/Layout.story.js
  src/components/Layout/Row.js
  src/components/Layout/index.scss
Labels: :robot: 24 hrs, :robot: 4 hrs

#1264 fix (Input): Restore `focus` prop that was inadvertently removed
  CHANGELOG.md
  src/components/ExampleComponent/tests/__snapshots__/index.js.snap
  src/components/FilterPicker/tests/__snapshots__/index.js.snap
  src/components/Input/index.js
  src/components/Input/tests/index.js
Labels: :robot: 4 hrs, :robot: 6 hrs

#1266 fix (Contributing) Update merge and release instructions
  CONTRIBUTING.md
Labels: :robot: 2 hrs
