Repository optimizely/oui, pull requests merged in 2019-09, with the labels that each got.

#1218 patch(Poptip): Prevent Poptip to display "undefined" on hover when disabled
  CHANGELOG.md
  src/components/Poptip/index.js
Labels: :robot: 12 hrs, :robot: 4 hrs

#1190 feat(PaginationControls): New component for updated pagination design
  CHANGELOG.md
  package.json
  src/components/Link/index.js
  src/components/Link/tests/__snapshots__/index.js.snap
  src/components/Link/tests/index.js
  src/components/PaginationControls/PaginationControls.story.js
  src/components/PaginationControls/index.js
  src/components/PaginationControls/index.scss
  src/components/PaginationControls/tests/index.js
  src/main.js
  src/oui/_oui-partials.scss
  src/utils/custom-prop-types.js
Labels: :robot: 24 hrs, :robot: 4 hrs

#1222 Drau/security fixes
  CHANGELOG.md
  package.json
  yarn.lock
Labels: :robot: 4 hrs, :robot: 6 hrs
