Repository optimizely/oui, pull requests merged in 2019-07, with the labels that each got.

#1185 patch (TokensInput) Add addOnBlur and addOnPaste props
  CHANGELOG.md
  src/components/TokensInput/index.js
Labels: :robot: 4 hrs, :robot: 6 hrs

#1192 Revert "Upgrade storybook to 5.1.9"
  yarn.lock
Labels: :robot: 2 hrs

#1184 feat(ButtonIcon): New component for square button icons
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  src/components/ButtonIcon/ButtonIcon.story.js
  src/components/ButtonIcon/index.js
  src/components/ButtonIcon/index.scss
  src/components/ButtonIcon/tests/index.js
  src/components/Icon/index.scss
  src/main.js
  src/oui/_oui-partials.scss
  src/tokens/forimport/_index.scss
  src/tokens/forimport/index.cjs.js
  src/tokens/forimport/index.es.js
  src/tokens/src/size.json
Labels: :robot: 24 hrs, :robot: 4 hrs

#1187 Drau/layout example
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  src/components/Layout/Layout.story.js
  src/components/Layout/index.scss
Labels: :robot: 1 hrs

#1201 Update node version for running tests/builds to v12.4.0
  .nvmrc
  .travis.yml
  CHANGELOG.md
  package.json
  yarn.lock
Labels: :robot: 12 hrs, :robot: 4 hrs

#1195 Add optional fillColorName property to RangeSlider
  CHANGELOG.md
  src/components/RangeSlider/Rangeslider.story.js
  src/components/RangeSlider/constants.js
  src/components/RangeSlider/index.js
  src/components/RangeSlider/index.scss
  src/components/RangeSlider/tests/__snapshots__/index.js.snap
  src/components/RangeSlider/tests/index.js
  src/oui/_oui-variables.scss
Labels: :robot: 4 hrs

#1203 Drau/csswhat-build-always
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  package.json
Labels: :robot: 1 hrs

#1202 Drau/codediff table tightening
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  src/components/CodeDiff/CodeDiff.story.js
  src/components/CodeDiff/index.js
  src/components/CodeDiff/overrides.scss
  src/components/Table/TR/index.js
  src/components/Table/index.scss
Labels: :robot: 1 hrs
