Repository optimizely/oui, pull requests merged in 2019-06, with the labels that each got.

#1167 feat(storybook): Upgrade to 5.1 and add withInfo to all stories by default
  .storybook/config.js
  src/components/Accordion/Accordion.story.js
  src/components/ArrowsInline/ArrowInline.story.js
  src/components/Attention/Attention.story.js
  src/components/Autocomplete/Autocomplete.story.js
  src/components/Badge/Badge.story.js
  src/components/BlockList/BlockList.story.js
  src/components/Button/Button.story.js
  src/components/ButtonRow/ButtonRow.story.js
  src/components/Card/Card.story.js
  src/components/Checkbox/Checkbox.story.js
  src/components/Code/Code.story.js
  src/components/CopyButton/CopyButton.story.js
  src/components/DatePicker/DatePicker.story.js
  src/components/DatePicker/DateRangePicker.story.js
  src/components/Dialog/Dialog.story.js
  src/components/Disclose/Disclose.story.js
  src/components/DiscloseTable/DiscloseTable.story.js
  src/components/Dropdown/Dropdown.story.js
  src/components/ExampleComponent/ExampleComponent.story.js
  src/components/FilterPicker/FilterPicker.story.js
  src/components/HelpPopover/HelpPopover.story.js
  src/components/Input/Input.story.js
  src/components/Label/Label.story.js
  src/components/Link/Link.story.js
  src/components/OverlayWrapper/OverlayWrapper.story.js
  src/components/Pagination/Pagination.story.js
  src/components/Popover/Popover.story.js
  src/components/Poptip/Poptip.story.js
  src/components/ProgressBar/ProgressBar.story.js
  src/components/ProgressDots/ProgressDots.story.js
  src/components/Radio/Radio.story.js
  src/components/RangeSlider/Rangeslider.story.js
  src/components/Select/Select.story.js
  src/components/SelectDropdown/SelectDropdown.story.js
  src/components/Sheet/Sheet.story.js
  src/components/Sidebar/Sidebar.story.js
  src/components/Sortable/DragAndDrop.story.js
  src/components/Spinner/Spinner.story.js
  src/components/Steps/Steps.story.js
  src/components/Switch/Switch.story.js
  src/components/TabNav/TabNav.story.js
  src/components/Table/Table.story.js
  src/components/TextField/TextField.story.js
  src/components/Textarea/Textarea.story.js
  src/components/Token/Token.story.js
  src/components/TokensInput/TokensInput.story.js
  src/components/Toolbar/Toolbar.story.js
  yarn.lock
Labels: :robot: 4 hrs, :robot: 6 hrs

#1170 fix (TokensInput) extraAddKeys prop-types check
  CHANGELOG.md
  src/components/TokensInput/index.js
Labels: :robot: 1 hrs

#1161 Storybook color and stats automation
  .storybook/borderradius.story.js
  .storybook/config.js
  .storybook/css.story.js
  .storybook/overview.story.js
  .travis.yml
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  data/oui.css.json
  data/oui.css/oui.css
  data/styles.css.json
  package.json
  yarn.lock
Labels: :robot: 0.2 hrs

#1172 Prep for moving icons into OUI repo
  CHANGELOG.md
  icons/all_icon_data.json
Labels: :robot: 0.2 hrs

#1173 fix(progress-dots): Prevent wrapping of dots
  CHANGELOG.md
  src/components/ProgressDots/index.scss
Labels: :robot: 0.1 hrs

#1176 feat(selectDropdown): Add ability to provide a placeholder
  CHANGELOG.md
  src/components/SelectDropdown/SelectDropdown.story.js
  src/components/SelectDropdown/index.js
  src/components/SelectDropdown/tests/index.js
Labels: :robot: 1 hrs

#1175 feat (TokensInput) Add more event handlers
  CHANGELOG.md
  src/components/TokensInput/index.js
  src/components/TokensInput/tests/index.js
Labels: :robot: 4 hrs, :robot: 8 hrs

#1180 Initial capitalize all Storybook names
  CHANGELOG.md
  data/csswhat/oui.css.json
  src/components/ArrowsInline/ArrowInline.story.js
  src/components/Attention/Attention.story.js
  src/components/Autocomplete/Autocomplete.story.js
  src/components/Badge/Badge.story.js
  src/components/BlockList/BlockList.story.js
  src/components/ButtonRow/ButtonRow.story.js
  src/components/Card/Card.story.js
  src/components/Checkbox/Checkbox.story.js
  src/components/Code/Code.story.js
  src/components/CopyButton/CopyButton.story.js
  src/components/DatePicker/DatePicker.story.js
  src/components/DatePicker/DateRangePicker.story.js
  src/components/Disclose/Disclose.story.js
  src/components/DiscloseTable/DiscloseTable.story.js
  src/components/HelpPopover/HelpPopover.story.js
  src/components/Input/Input.story.js
  src/components/Label/Label.story.js
  src/components/Link/Link.story.js
  src/components/OverlayWrapper/OverlayWrapper.story.js
  src/components/Pagination/Pagination.story.js
  src/components/Popover/Popover.story.js
  src/components/Poptip/Poptip.story.js
  src/components/ProgressDots/ProgressDots.story.js
  src/components/Radio/Radio.story.js
  src/components/RangeSlider/Rangeslider.story.js
  src/components/Select/Select.story.js
  src/components/SelectDropdown/SelectDropdown.story.js
  src/components/Sheet/Sheet.story.js
  src/components/Sidebar/Sidebar.story.js
  src/components/Spinner/Spinner.story.js
  src/components/Steps/Steps.story.js
  src/components/Table/Table.story.js
  src/components/Textarea/Textarea.story.js
  src/components/TokensInput/TokensInput.story.js
  src/components/Toolbar/Toolbar.story.js
  src/stories/icons-example.story.js
  src/stories/login-example.story.js
Labels: :robot: 4 hrs, :robot: 6 hrs

#1182 Drau/data oui component
  CHANGELOG.md
  src/components/Dialog/Deprecated/Wrapper/index.js
  src/components/Dialog/index.js
  src/components/Dropdown/index.js
  src/components/Dropdown/tests/__snapshots__/index.js.snap
  src/components/EmptyDashboard/index.js
  src/components/EmptyDashboard/tests/__snapshots__/index.js.snap
  src/components/Link/index.js
  src/components/Link/tests/__snapshots__/index.js.snap
  src/components/Sheet/index.js
  src/components/Steps/index.js
  src/components/Toolbar/index.js
Labels: :robot: 4 hrs, :robot: 8 hrs
