Repository optimizely/oui, pull requests merged in 2019-08, with the labels that each got.

#1207 feat(SelectDropdown): Add ability to specify maxWidth
  CHANGELOG.md
  src/components/Button/index.js
  src/components/Button/tests/index.js
  src/components/SelectDropdown/SelectDropdown.story.js
  src/components/SelectDropdown/index.js
  src/components/SelectDropdown/index.scss
  src/components/SelectDropdown/tests/index.js
  src/oui/_oui-partials.scss
Labels: :robot: 2 hrs

#1208 Adds nearest design token colors to Storybook
  .storybook/css.story.js
  .storybook/overview.story.js
  .storybook/preview-head.html
  0
  CHANGELOG.md
  package.json
  yarn.lock
Labels: :robot: 0.1 hrs

#1204 update contributing docs to be clear about v`99.xx.xx`
  CONTRIBUTING.md
Labels: :robot: 24 hrs, :robot: 4 hrs

#1205 feat(DatePicker): Add isFutureDateSelectable and initialVisibleMonth props
  CHANGELOG.md
  src/components/DatePicker/DatePicker.js
  src/components/DatePicker/DatePicker.story.js
  src/components/DatePicker/DateRangePicker.js
  src/components/DatePicker/DateRangePicker.story.js
  src/components/DatePicker/fns.js
  src/components/DatePicker/overrides.scss
  src/components/DatePicker/tests/index.js
Labels: :robot: 2 hrs

#1213 perf (OverlayWrapper)[UXENG-27]: Lazily instantiate tether for performance reasons
  src/components/HelpPopover/tests/__snapshots__/index.js.snap
  src/components/OverlayWrapper/index.js
  src/components/OverlayWrapper/tests/__snapshots__/index.js.snap
  src/components/OverlayWrapper/tests/index.js
Labels: :robot: 0.2 hrs

#1211 feat(emptyDashboard)[APPX-729]: Update EmptyDashboard component to place button in top right corner
  CHANGELOG.md
  CONTRIBUTING.md
  src/components/EmptyDashboard/EmptyDashboard.story.js
  src/components/EmptyDashboard/index.js
  src/components/EmptyDashboard/index.scss
  src/components/EmptyDashboard/tests/__snapshots__/index.js.snap
  src/components/EmptyDashboard/tests/index.js
  src/oui/_oui-partials.scss
Labels: :robot: 4 hrs, :robot: 6 hrs

#1216 Textarea patch on numRows
  CHANGELOG.md
  src/components/Textarea/Textarea.story.js
  src/components/Textarea/index.js
  src/components/Textarea/index.scss
  src/components/Textarea/tests/index.js
Labels: :robot: 0.1 hrs

#1212 feat(NavBar): Added a new Navigation bar component.
  CHANGELOG.md
  src/components/NavBar/CurrentUserMenu/AccountSwitcher/index.js
  src/components/NavBar/CurrentUserMenu/AccountSwitcher/tests/index.js
  src/components/NavBar/CurrentUserMenu/index.js
  src/components/NavBar/CurrentUserMenu/tests/index.js
  src/components/NavBar/IconLink/index.js
  src/components/NavBar/IconLink/tests/index.js
  src/components/NavBar/NavBar.story.js
  src/components/NavBar/index.js
  src/components/NavBar/index.scss
  src/components/NavBar/tests/index.js
  src/main.js
  src/oui/_oui-partials.scss
Labels: :robot: 16 hrs, :robot: 4 hrs
