Repository optimizely/oui, pull requests merged in 2019-05, with the labels that each got.

#1152 feat(code/copy-button): Add ability to style copy button
  CHANGELOG.md
  src/components/Code/Code.story.js
  src/components/Code/index.js
  src/components/CopyButton/CopyButton.story.js
  src/components/CopyButton/index.js
Labels: :robot: 1 hrs

#1151 feat(sheet/dialog): Updates to allow for node in subtitle
  src/components/Dialog/Dialog.story.js
  src/components/Dialog/index.js
  src/components/Dialog/tests/index.js
  src/components/Sheet/Sheet.story.js
  src/components/Sheet/index.js
  src/components/Sheet/tests/index.js
Labels: :robot: 2 hrs

#1156 fix babel config to properly export es5 and esm with babel 7
  babel.config.js
  package.json
Labels: :robot: 0.1 hrs

#1135 feat(button): Add new button that disables and adds spinner
  CHANGELOG.md
  src/components/Button/Button.story.js
  src/components/Button/index.js
  src/components/Button/index.scss
  src/components/Button/tests/__snapshots__/index.js.snap
  src/components/Button/tests/index.js
  src/components/CopyButton/tests/__snapshots__/index.js.snap
  src/components/EmptyDashboard/tests/__snapshots__/index.js.snap
  src/components/ExampleComponent/tests/__snapshots__/index.js.snap
  src/components/FilterPicker/tests/__snapshots__/index.js.snap
Labels: :robot: 2 hrs

#1162 Update token color to use blue-base per Ron
  CHANGELOG.md
  src/components/Token/Token.story.js
  src/components/Token/index.scss
  src/oui/_oui-variables.scss
Labels: :robot: 24 hrs, :robot: 4 hrs

#1164 feat(DateRangePicker): Export component
  CHANGELOG.md
  src/main.js
Labels: :robot: 0.1 hrs

#1165 patch(DatePicker): Properly export DatePicker and DateRangePicker
  CHANGELOG.md
  src/components/DatePicker/DatePicker.js
  src/components/DatePicker/DateRangePicker.js
  src/main.js
Labels: :robot: 0.1 hrs

#1163 Drau/sidebar knobs and misc Storybook fixes
  src/components/ExampleComponent/ExampleComponent.story.js
  src/components/ExampleComponent/index.scss
  src/components/Sidebar/Sidebar.story.js
  src/oui/partials/layout/_reading-column.scss
  src/stories/icons-example.story.js
Labels: :robot: 24 hrs, :robot: 4 hrs
