Repository optimizely/oui, pull requests merged in 2019-02, with the labels that each got.

#1117 perf fix (Popper): Conditionally render <Popper> based on open & disabled state
  CHANGELOG.md
  src/components/Dropdown/index.js
  src/components/Dropdown/tests/__snapshots__/index.js.snap
  src/components/Dropdown/tests/index.js
Labels: :robot: 0.2 hrs

#1116 feat (TokensInput): Handle pasted content better and enable any addKeys
  CHANGELOG.md
  src/components/TokensInput/TokensInput.story.js
  src/components/TokensInput/index.js
  src/components/TokensInput/tests/index.js
Labels: :robot: 1 hrs

#1121 Add Immutable to OUI
  package.json
  yarn.lock
Labels: :robot: 4 hrs

#1122 Drau/fix webpack dev server vulnerability
  CHANGELOG.md
  package.json
  yarn.lock
Labels: :robot: 12 hrs, :robot: 4 hrs

#1123 feat(TokensInput)[REC-751][REC-760][REC-762]: Added addOnBlur, flexing, minWidth, and placeholder with maxTags for input of TokensInput.
  CHANGELOG.md
  src/components/TokensInput/index.js
  src/components/TokensInput/tests/index.js
Labels: :robot: 1 hrs, react, ui

#1125 fix(tokensInput): Tighten spacing around keyword tokens
  CHANGELOG.md
  src/components/Token/Token.story.js
  src/components/Token/index.js
  src/components/Token/index.scss
  src/components/Token/tests/index.js
  src/components/TokensInput/index.js
  src/components/TokensInput/tests/index.js
Labels: :robot: 0.2 hrs

#1126 Encode hex `#` character as `%23` encoded character
  CHANGELOG.md
  src/components/RangeSlider/Rangeslider.story.js
  src/components/RangeSlider/index.scss
  src/oui/partials/sass/_functions.scss
Labels: :robot: 4 hrs

#1129 fix (OUI) Lockdown highlight.js version
  package.json
Labels: :robot: 0.2 hrs
