Repository optimizely/oui, pull requests merged in 2019-11, with the labels that each got.

#1244 fix(SelectDropdown): Reduce padding for select dropdown button
  CHANGELOG.md
  src/components/SelectDropdown/index.js
Labels: :robot: 4 hrs

#1243 fix(textarea): Remove hardcoded height, move to input
  CHANGELOG.md
  src/components/Input/index.scss
  src/oui/partials/elements/_form.scss
Labels: :robot: 4 hrs, :robot: 8 hrs

#1254 fix(help-popover): Convert to ButtonIcon and open on focus
  CHANGELOG.md
  src/components/ButtonIcon/index.js
  src/components/HelpPopover/index.js
  src/components/HelpPopover/tests/__snapshots__/index.js.snap
  src/components/HelpPopover/tests/index.js
  src/components/OverlayWrapper/index.js
  src/components/OverlayWrapper/tests/__snapshots__/index.js.snap
  src/components/Popover/index.js
  src/components/Popover/tests/index.js
Labels: :robot: 16 hrs, :robot: 4 hrs

#1256 Cleanup input and make it forward refs
  CHANGELOG.md
  src/components/ExampleComponent/tests/__snapshots__/index.js.snap
  src/components/FilterPicker/tests/__snapshots__/index.js.snap
  src/components/Input/index.js
  src/components/Input/tests/index.js
  yarn.lock
Labels: :robot: 4 hrs, :robot: 8 hrs

#1250 feat (Dropdown): Dropdown and SelectDropdown updates
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  package.json
  src/components/Dropdown/Dropdown.story.js
  src/components/Dropdown/DropdownBlockLink/index.js
  src/components/Dropdown/DropdownBlockLink/tests/index.js
  src/components/Dropdown/DropdownContents/index.js
  src/components/Dropdown/DropdownContents/tests/index.js
  src/components/Dropdown/DropdownListItem/index.js
  src/components/Dropdown/DropdownListItem/tests/index.js
  src/components/Dropdown/index.js
  src/components/Dropdown/index.scss
  src/components/Dropdown/tests/__snapshots__/index.js.snap
  src/components/Dropdown/tests/index.js
  src/components/NavBar/CurrentUserMenu/index.js
  src/components/SelectDropdown/index.js
  src/components/SelectDropdown/tests/index.js
Labels: :robot: 24 hrs, :robot: 4 hrs
