Repository optimizely/oui, pull requests merged in 2020-10, with the labels that each got.

#1425 performance (DragAndDrop) Memoize DraggableItem props
  CHANGELOG.md
  src/components/DragAndDrop/DraggableItem/index.js
Labels: :robot: 0.2 hrs

#1424 update(Sidebar): Add prop to make sidebar sticky and add overflow classes in css
  CHANGELOG.md
  data/oui.css/oui.css
  src/components/Sidebar/Sidebar.js
  src/components/Sidebar/Sidebar.story.js
  src/components/Sidebar/tests/index.js
  types/index.d.ts
Labels: :robot: 0.2 hrs

#1427 patch(Tile)[APPX-2261]: Add unsaved changes indicator
  CHANGELOG.md
  src/components/Tile/Tile.story.tsx
  src/components/Tile/index.tsx
  src/components/Tile/tests/index.js
Labels: :robot: 0.2 hrs

#1426 revert (DragAndDrop) DraggableItem memoization caused bugs
  CHANGELOG.md
  src/components/DragAndDrop/DraggableItem/index.js
Labels: :robot: 1 hrs

#1429 feat(ButterBar)[OPP-349]: add ButterBar component to OUI
  .storybook/overview.story.js
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  src/components/ButterBar/ButterBar.story.js
  src/components/ButterBar/index.scss
  src/components/ButterBar/index.tsx
  src/components/ButterBar/tests/index.js
  src/main.js
  src/oui/_oui-partials.scss
Labels: :robot: 2 hrs

#1432 update(Sidebar): Allow sidebar to be resizable on horizontal axis
  CHANGELOG.md
  package.json
  src/components/Sidebar/Sidebar.js
  src/components/Sidebar/Sidebar.story.js
  src/components/Sidebar/tests/index.js
  types/index.d.ts
  yarn.lock
Labels: :robot: 2 hrs
