Repository optimizely/oui, pull requests merged in 2020-06, with the labels that each got.

#1350 feat(Tile): New component for Tile
  CHANGELOG.md
  src/components/ButtonIcon/index.js
  src/components/Card/Card.story.js
  src/components/DragAndDrop/DragAndDrop.story.js
  src/components/Tile/Tile.story.js
  src/components/Tile/index.scss
  src/components/Tile/index.tsx
  src/components/Tile/tests/index.js
  src/components/Token/index.js
  src/main.js
  src/oui/_oui-partials.scss
  src/stories/icons-example.story.js
  types/index.d.ts
  types/templates/module-declaration.d.ts
Labels: :robot: 24 hrs, :robot: 4 hrs

#1355 feat (SearchPicker) Add Storybook example for SearchPicker in a Dropdown
  CHANGELOG.md
  src/components/SearchPicker/SearchPicker.story.js
Labels: :robot: 4 hrs, :robot: 6 hrs

#1357 feat(LayoutKit): Add more layout examples and Col align self
  CHANGELOG.md
  src/components/Layout/Col.tsx
  src/components/Layout/Layout.story.js
  src/components/Layout/Templates.story.js
  src/components/SearchPicker/SearchPicker.story.js
Labels: :robot: 4 hrs

#1358 feat(Tile): Update dropdownItems to take Dropdown ListItems
  CHANGELOG.md
  src/components/Dropdown/DropdownBlockLinkText/index.js
  src/components/Dropdown/DropdownListItem/index.js
  src/components/Tile/Tile.story.js
  src/components/Tile/index.tsx
  src/components/Tile/tests/index.js
  types/index.d.ts
Labels: :robot: 12 hrs, :robot: 4 hrs

#1364 patch(Tile): Add test sections
  CHANGELOG.md
  src/components/Tile/Tile.story.js
  src/components/Tile/Tile.story.tsx
  src/components/Tile/index.tsx
Labels: :robot: 2 hrs

#1363 feat (Table) Add forward ref to table row component
  CHANGELOG.md
  src/components/Table/TR/index.js
  types/index.d.ts
Labels: :robot: 4 hrs
