Repository optimizely/oui, pull requests merged in 2020-02, with the labels that each got.

#1290 patch(HelpPopover): Add example of inline with text
  src/components/HelpPopover/HelpPopover.story.js
  src/components/HelpPopover/index.js
  src/components/HelpPopover/tests/__snapshots__/index.js.snap
Labels: :robot: 4 hrs, :robot: 6 hrs

#1289 Upgrade Storybook to 5.3.10 and add Storysource
  .storybook/AppFrame.story.js
  .storybook/addons.js
  .storybook/borderradius.story.js
  .storybook/config.js
  .storybook/css.story.js
  .storybook/overview.story.js
  .storybook/tokens.story.js
  .storybook/webpack.config.js
  package.json
  src/components/ButtonIcon/ButtonIcon.story.js
  src/components/Code/Code.story.js
  src/components/DockedFooter/DockedFooter.story.js
  src/components/ExampleComponent/ExampleComponent.story.js
  src/components/Layout/Layout.story.js
  src/components/Table/TD/index.js
  src/components/Toolbar/index.js
  src/stories/icons-example.story.js
  yarn.lock
Labels: :robot: 6 hrs

#1294 fix(Code): Don't wrap text inside Code component (block mode)
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  src/components/Code/Code.story.js
  src/components/Code/index.scss
Labels: :robot: 2 hrs

#1291 feat(Avatar): New avatar component
  CHANGELOG.md
  src/components/Avatar/avatar.story.js
  src/components/Avatar/index.js
  src/components/Avatar/index.scss
  src/components/Avatar/tests/index.js
  src/components/NavBar/CurrentUserMenu/index.js
  src/components/NavBar/index.scss
  src/main.js
  src/oui/_oui-partials.scss
Labels: :robot: 24 hrs, :robot: 4 hrs

#1299 fix: Releasing OUI to NPM is failing, try setting `edge: true`
  .travis.yml
Labels: :robot: 0.1 hrs

#1300 patch(Button): Update focus and hover states for buttons
  .gitignore
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  src/components/Button/Button.story.js
  src/components/Button/index.scss
Labels: :robot: 1 hrs

#1293 feat(SelectDropdown): Add ability to add label to select dropdown
  CHANGELOG.md
  src/components/Dropdown/DropdownBlockLink/index.js
  src/components/Input/Input.story.js
  src/components/Input/index.scss
  src/components/SelectDropdown/SelectDropdown.story.js
  src/components/SelectDropdown/index.js
  src/components/SelectDropdown/tests/index.js
  types/index.d.ts
Labels: :robot: 24 hrs, :robot: 4 hrs

#1199 feat(buttonIcon): Add ability to specify iconFill color
  CHANGELOG.md
  src/components/ButtonIcon/ButtonIcon.story.js
  src/components/ButtonIcon/index.js
  src/components/ButtonIcon/tests/index.js
  src/components/RangeSlider/Rangeslider.story.js
  src/components/RangeSlider/constants.js
  src/components/RangeSlider/index.js
  src/components/RangeSlider/tests/index.js
  src/utils/accessibility.js
Labels: :robot: 0.2 hrs

#1301 feat(Token): Update Token to take in dragHandleProps
  CHANGELOG.md
  src/components/DragAndDrop/DragAndDrop.story.js
  src/components/DragAndDrop/tests/index.js
  src/components/Token/Token.story.js
  src/components/Token/index.js
  src/components/Token/index.scss
  src/overrides/Layout/index.scss
Labels: :robot: 4 hrs
