Repository optimizely/oui, pull requests merged in 2020-01, with the labels that each got.

#1271 patch(Webpack): Allow Babel to run on OUI imports requiring it
  CHANGELOG.md
  CONTRIBUTING.md
  package.json
  webpack.config.js
Labels: :robot: 0.2 hrs

#1272 feat(layout): updates to vertically align a row and add scroll to col
  CHANGELOG.md
  src/components/Layout/Col.js
  src/components/Layout/Layout.story.js
  src/components/Layout/Row.js
  src/components/Layout/index.scss
Labels: :robot: 2 hrs

#1270 feat(Dropdown): Add ability to render label version easily
  CHANGELOG.md
  src/components/Dropdown/Dropdown.story.js
  src/components/Dropdown/DropdownContents/index.js
  src/components/Dropdown/index.js
  src/components/Dropdown/tests/__snapshots__/index.js.snap
  src/components/Dropdown/tests/index.js
  src/overrides/Layout/index.scss
Labels: :robot: 16 hrs, :robot: 4 hrs

#1273 feat(dropdown): Add ability to support multi select
  CHANGELOG.md
  src/components/Dropdown/Dropdown.story.js
  src/components/Dropdown/DropdownBlockLink/index.js
  src/components/Dropdown/DropdownBlockLink/tests/__snapshots__/index.js.snap
  src/components/Dropdown/DropdownBlockLink/tests/index.js
  src/components/SelectDropdown/SelectDropdown.story.js
  src/components/SelectDropdown/index.js
  src/components/SelectDropdown/tests/index.js
Labels: :robot: 12 hrs, :robot: 4 hrs

#1253 feat (SearchPicker): Initial search picker component and story
  .storybook/preview-head.html
  src/components/Dropdown/index.js
  src/components/SearchPicker/SearchPicker.story.js
  src/components/SearchPicker/index.js
  src/components/SearchPicker/mock_api/index.js
  src/components/SearchPicker/mock_api/mock_data.js
  src/components/SearchPicker/tests/__snapshots__/index.js.snap
  src/components/SearchPicker/tests/index.js
  src/main.js
  src/setupTests.js
  src/utils/accessibility.js
  src/utils/tests/accessibility.js
  tsconfig.json
Labels: :robot: 1 hrs

#1277 remove(CodeDiffLegacy)[APPX-1337]: Remove deprecated component in favor of CodeDiff
  CHANGELOG.md
  src/components/CodeDiff/CodeDiffLegacy.js
  src/components/CodeDiff/index.js
  src/components/CodeDiff/index.scss
  src/main.js
Labels: :robot: 1 hrs

#1268 chore (Typescript): Enable Typescript and auto generate declaration files
  .babelrc
  .storybook/webpack.config.js
  CONTRIBUTING.md
  README.md
  jest.config.js
  package.json
  src/components/Attention/index.js
  src/components/Attention/index.tsx
  src/components/ExampleComponent/tests/__snapshots__/index.js.snap
  tsconfig.json
  types/README.md
  types/index.d.ts
  types/oui.d.ts
  types/templates/module-declaration.d.ts
  webpack.config.js
  yarn.lock
Labels: :robot: 2 hrs

#1283 chore (Docs): Add docs for Typescript
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
Labels: :robot: 0.1 hrs

#1261 feat(DragAndDrop): New component to handle dynamic drag and drop
  CHANGELOG.md
  package.json
  src/components/DragAndDrop/DragAndDrop.story.js
  src/components/DragAndDrop/DraggableItem/index.js
  src/components/DragAndDrop/index.js
  src/components/DragAndDrop/tests/index.js
  src/components/Sortable/Sortable.story.js
  src/main.js
  yarn.lock
Labels: :robot: 4 hrs, :robot: 8 hrs

#1281 fix (SearchPicker) Allow for an offset in search picker children
  src/components/SearchPicker/SearchPicker.story.js
  src/components/SearchPicker/tests/__snapshots__/index.js.snap
  src/utils/accessibility.js
  src/utils/tests/accessibility.js
Labels: :robot: 4 hrs

#1284 fix (SearchPicker) Wait for all queries to complete before showing result summary
  CHANGELOG.md
  src/components/SearchPicker/index.js
  src/components/SearchPicker/tests/index.js
Labels: :robot: 4 hrs
