Repository optimizely/oui, pull requests merged in 2020-03, with the labels that each got.

#1305 fix(Navbar): Fix prop-type warnings in <NavBar>
  CHANGELOG.md
  src/components/NavBar/CurrentUserMenu/AccountSwitcher/index.js
  src/components/NavBar/CurrentUserMenu/AccountSwitcher/tests/index.js
  src/components/NavBar/IconLink/index.js
  src/components/NavBar/index.js
Labels: :robot: 1 hrs

#1303 feat(Storybook): Add chromatic VRT plus travis script
  .storybook/config.js
  .storybook/css.story.js
  .travis.yml
  CHANGELOG.md
  package.json
  scripts/run-chromatic.sh
  src/components/DatePicker/DatePicker.story.js
  src/components/DatePicker/DateRangePicker.story.js
  src/components/Link/Link.story.js
  yarn.lock
Labels: :robot: 12 hrs, :robot: 4 hrs

#1306 Update Readme for Chromatic
  CONTRIBUTING.md
  README.md
Labels: :robot: 2 hrs

#1274 fix(textarea): add required mark to text area label
  CHANGELOG.md
  src/components/Textarea/Textarea.story.js
  src/components/Textarea/index.js
  src/components/Textarea/tests/index.js
Labels: :robot: 24 hrs, :robot: 4 hrs

#1307 fix(typography): Update muted class color
  CHANGELOG.md
  src/oui/_oui-variables.scss
Labels: :robot: 12 hrs, :robot: 4 hrs

#1308 fix(NavBar): Add height adjustment to NavBar
  CHANGELOG.md
  src/components/NavBar/NavBar.story.js
  src/components/NavBar/index.scss
Labels: :robot: 4 hrs

#1309 Update chromatic dependency
  CHANGELOG.md
  package.json
  yarn.lock
Labels: :robot: 0.1 hrs
