Repository optimizely/oui, pull requests merged in 2020-08, with the labels that each got.

#1390 feat (SearchPicker) Add a customer filter-function for search results
  CHANGELOG.md
  src/components/SearchPicker/index.js
  src/components/SearchPicker/tests/index.js
Labels: :robot: 12 hrs

#1395 patch(Dropdown) [UXENG-138] Changed string to node for DropdownBlockLinkText and DropdownBlockLinkSecondaryText
  CHANGELOG.md
  src/components/Dropdown/DropdownBlockLinkSecondaryText/index.js
  src/components/Dropdown/DropdownBlockLinkSecondaryText/tests/index.js
  src/components/Dropdown/DropdownBlockLinkText/index.js
  src/components/Dropdown/DropdownBlockLinkText/tests/index.js
Labels: :robot: 0.1 hrs

#1396 feat(DatePicker) [UXENG-147] Add clear button to DatePicker and DateRangePicker
  CHANGELOG.md
  src/components/DatePicker/DatePicker.js
  src/components/DatePicker/DatePicker.story.js
  src/components/DatePicker/DateRangePicker.js
  src/components/DatePicker/DateRangePicker.story.js
  src/components/DatePicker/tests/index.js
Labels: :robot: 2 hrs

#1393 feat(Link) Add leftIcon and rightIcon props to Link
  CHANGELOG.md
  src/components/Button/Button.story.js
  src/components/Button/index.js
  src/components/Link/Link.story.js
  src/components/Link/index.js
  types/index.d.ts
Labels: :robot: 12 hrs, :robot: 4 hrs

#1399 Add automatic Changelog updater action
  .github/pull_request_template.md
  .github/workflows/main.yml
  .github_actions/ReadMe.md
  .github_actions/action.yml
  .github_actions/dist/index.js
  .github_actions/index.js
  .github_actions/package.json
  CHANGELOG.md
Labels: :robot: 0.2 hrs

#1398 feat(tokens): Update Color design tokens
  .storybook/tokens.story.js
  CHANGELOG.md
  src/tokens/forimport/_index.scss
  src/tokens/forimport/index.cjs.js
  src/tokens/forimport/index.es.js
  src/tokens/src/color.json
  src/utils/accessibility.js
  types/index.d.ts
Labels: :robot: 24 hrs, :robot: 4 hrs

#1403 patch(HelperClasses): Enforce flex classes
  CHANGELOG.md
  src/components/Token/index.js
  src/oui/partials/layout/_flexbox.scss
Labels: :robot: 0.2 hrs

#1405 patch(HelperClasses): Update flex--1 class
  CHANGELOG.md
  src/oui/partials/layout/_flexbox.scss
Labels: :robot: 0.2 hrs

#1391 [UXENG-4] Adding helper classes for div styling
  .storybook/helper_classes/backgroundColor.tsx
  .storybook/helper_classes/border.tsx
  .storybook/helper_classes/data.json
  .storybook/helper_classes/divStyling.story.tsx
  .storybook/helper_classes/flexbox.story.tsx
  .storybook/helper_classes/index.scss
  .storybook/helper_classes/sizing.tsx
  .storybook/helper_classes/spacing.story.tsx
  .storybook/helper_classes/typography.story.tsx
  CHANGELOG.md
Labels: :robot: 4 hrs

#1408 Update SelectDropdown to support labels and notes
  CHANGELOG.md
  src/components/Button/index.js
  src/components/Button/tests/index.js
  src/components/Dropdown/DropdownContents/index.tsx
  src/components/SelectDropdown/SelectDropdown.story.js
  src/components/SelectDropdown/index.js
  src/components/SelectDropdown/tests/index.js
  types/index.d.ts
Labels: :robot: 1 hrs

#1410 fix (Tile) Allow Tile to render string or React element as description
  CHANGELOG.md
  src/components/Tile/index.tsx
Labels: :robot: 0.2 hrs

#1409 Upgrade react-oui-icons to 2.11.1
  CHANGELOG.md
  package.json
  src/stories/icons.json
  yarn.lock
Labels: :robot: 4 hrs, :robot: 6 hrs
