Repository optimizely/oui, pull requests merged in 2020-05, with the labels that each got.

#1320 feat(Input): Add ability for icons on left and right and clear button
  CHANGELOG.md
  src/components/Input/Input.story.js
  src/components/Input/index.scss
  src/components/Input/index.tsx
  src/components/Input/tests/index.js
  src/components/InputIcon/index.scss
Labels: :robot: 12 hrs, :robot: 4 hrs

#1329 patch(storybook): remove mock date to fix storybook knobs
  .storybook/config.js
  CHANGELOG.md
  CONTRIBUTING.md
  package.json
  src/components/DatePicker/DatePicker.story.js
  src/components/DatePicker/DateRangePicker.story.js
Labels: :robot: 4 hrs, :robot: 6 hrs

#1328 fix(Token): Update spacing between ordering and drag handle
  CHANGELOG.md
  src/components/Token/Token.story.js
  src/components/Token/index.js
  src/components/Token/index.scss
Labels: :robot: 12 hrs, :robot: 4 hrs

#1326 feat(PaginationControls): Add ability to supply href for links
  CHANGELOG.md
  src/components/Button/index.scss
  src/components/PaginationControls/PaginationControls.story.js
  src/components/PaginationControls/index.js
  src/components/PaginationControls/index.scss
  src/components/PaginationControls/tests/index.js
Labels: :robot: 24 hrs, :robot: 4 hrs

#1333 feat(CopyButton): Add option to use text label instead of icon
  CHANGELOG.md
  src/components/CopyButton/CopyButton.story.js
  src/components/CopyButton/index.js
  src/components/CopyButton/tests/__snapshots__/index.js.snap
  src/components/CopyButton/tests/index.js
Labels: :robot: 1 hrs

#1336 Update to react icons v2.9.0
  CHANGELOG.md
  package.json
  src/stories/icons.json
  yarn.lock
Labels: :robot: 0.2 hrs

#1337 patch(Token): Update to use new hamburger drag handle
  CHANGELOG.md
  src/components/Sortable/SortableGroup/index.js
  src/components/Sortable/index.scss
  src/components/Token/Token.story.js
  src/components/Token/index.js
  src/components/Token/index.scss
  types/index.d.ts
Labels: :robot: 4 hrs, :robot: 8 hrs

#1340 feat(oui-storybook)[UXENG-98]add icon, hover ability to dropdown component
  CHANGELOG.md
  src/components/Dropdown/Dropdown.story.js
  src/components/Dropdown/DropdownBlockLink/index.js
  src/components/Dropdown/DropdownBlockLink/tests/__snapshots__/index.js.snap
  src/components/Dropdown/DropdownBlockLink/tests/index.js
  src/components/Dropdown/DropdownBlockLinkText/index.js
  src/components/Dropdown/DropdownBlockLinkText/tests/index.js
  src/components/Dropdown/index.scss
  types/index.d.ts
Labels: :robot: 4 hrs, :robot: 6 hrs

#1347 fix(Switch): Update background color of off state
  CHANGELOG.md
  src/components/Switch/index.scss
  src/oui/_oui-variables.scss
Labels: :robot: 0.2 hrs

#1343 feat (Layout) Add ref options for Col and Row
  CHANGELOG.md
  src/components/Layout/Col.tsx
  src/components/Layout/Row.tsx
  types/index.d.ts
Labels: :robot: 0.2 hrs

#1349 fix(dropdown): Add default props for mouse enter and leave
  CHANGELOG.md
  src/components/Dropdown/DropdownBlockLink/index.js
  src/components/Dropdown/DropdownBlockLink/tests/__snapshots__/index.js.snap
Labels: :robot: 0.2 hrs

#1341 fix (DockedFooter) Simplify DockedFooter and update story
  CHANGELOG.md
  src/components/DockedFooter/DockedFooter.story.js
  src/components/DockedFooter/index.js
  types/index.d.ts
Labels: :robot: 1 hrs
