Repository optimizely/oui, pull requests merged in 2020-04, with the labels that each got.

#1313 feat(Select): Add ability to make select full width and have label
  CHANGELOG.md
  src/components/Select/Select.story.js
  src/components/Select/index.js
  src/components/Select/index.scss
  src/components/Select/tests/__snapshots__/index.js.snap
  src/components/Select/tests/index.js
  src/oui/partials/elements/_form.scss
Labels: :robot: 16 hrs, :robot: 4 hrs

#1319 feat(LayoutKitTemplate): Add ColWithNubbin for configuration panels
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  src/components/Layout/ColWithNubbin.tsx
  src/components/Layout/Container.tsx
  src/components/Layout/Layout.story.js
  src/components/Layout/Templates.story.js
  src/components/Layout/index.scss
  src/main.js
  src/tokens/forimport/_index.scss
  src/tokens/forimport/index.cjs.js
  src/tokens/forimport/index.es.js
  src/tokens/src/size.json
Labels: :robot: 12 hrs, :robot: 4 hrs

#1322 update(OUI): Upgrade react-oui-icons to 2.8.1
  CHANGELOG.md
  package.json
  src/stories/icons.json
  yarn.lock
Labels: dependencies
