Repository optimizely/oui, pull requests merged in 2020-09, with the labels that each got.

#1412 Update icons and reduce nav spacing
  CHANGELOG.md
  package.json
  src/components/NavBar/NavBar.story.js
  src/components/NavBar/index.js
  src/components/NavBar/index.scss
  src/stories/icons.json
  yarn.lock
Labels: :robot: 1 hrs

#1413 patch(Button): Update Plain style button
  CHANGELOG.md
  src/components/Button/index.scss
  src/components/SelectDropdown/index.js
Labels: :robot: 24 hrs, :robot: 4 hrs

#1416 feat(TokensInput): Add new styles and node type for Token
  CHANGELOG.md
  src/components/ButtonIcon/index.js
  src/components/SelectDropdown/index.js
  src/components/Token/DismissButton/index.js
  src/components/Token/DismissButton/tests/index.js
  src/components/Token/index.js
  src/components/Token/index.scss
  src/components/TokensInput/TokensInput.story.js
  src/components/TokensInput/index.js
  src/components/TokensInput/index.scss
  src/components/TokensInput/tests/index.js
  src/oui/_oui-partials.scss
  src/oui/partials/elements/_reset.scss
  src/utils/accessibility.js
  types/index.d.ts
Labels: :robot: 2 hrs

#1417 fix(SelectDropdown): Fixed Label click firing twice in Multiselect mode
  CHANGELOG.md
  src/components/BlockList/BlockList.story.js
  src/components/BlockList/example/index.js
  src/components/Button/Button.story.js
  src/components/Disclose/Disclose.story.js
  src/components/Disclose/example/index.js
  src/components/DiscloseTable/DiscloseTable.story.js
  src/components/DockedFooter/DockedFooter.story.js
  src/components/Dropdown/DropdownBlockLink/index.js
  src/components/Dropdown/DropdownBlockLink/tests/__snapshots__/index.js.snap
  src/components/ExampleComponent/ExampleComponent.story.js
  src/components/HelpPopover/HelpPopover.story.js
  src/components/ManagerSideNav/ManagerSideNav.story.js
  src/components/OverlayWrapper/example/index.js
  src/components/Sortable/SortDragLayer/index.js
  src/components/Spinner/Spinner.story.js
Labels: :robot: 4 hrs

#1418 feat (Tile) Add support for results link in Tile
  CHANGELOG.md
  src/components/Tile/Tile.story.tsx
  src/components/Tile/index.tsx
  src/components/Tile/tests/index.js
Labels: :robot: 4 hrs

#1419 fix(Token): fix proptype for name prop
  CHANGELOG.md
  src/components/Token/index.js
  types/index.d.ts
Labels: :robot: 1 hrs

#1420 update(DropdownBlockLink): replace defaultChecked by checked inside checkbox
  CHANGELOG.md
  src/components/Dropdown/DropdownBlockLink/index.js
  src/components/Dropdown/DropdownBlockLink/tests/__snapshots__/index.js.snap
  src/components/SelectDropdown/tests/index.js
Labels: :robot: 2 hrs

#1421 update(TokensInput): remove DismissButton from token when isDisabled is true
  CHANGELOG.md
  src/components/TokensInput/index.js
  src/components/TokensInput/tests/index.js
Labels: :robot: 2 hrs

#1422 feat(ButtonIcon)[APPX-2240]: Memoize ButtonIcon component
  CHANGELOG.md
  package.json
  src/components/BlockList/Item/tests/index.js
  src/components/Button/tests/index.js
  src/components/ButtonIcon/index.js
  src/components/Card/tests/index.js
  src/components/CodeDiff/tests/index.js
  src/components/CopyButton/tests/__snapshots__/index.js.snap
  src/components/DiscloseTable/Row/tests/index.js
  src/components/DiscloseTable/tests/index.js
  src/components/DragAndDrop/tests/index.js
  src/components/Dropdown/DropdownBlockLinkSecondaryText/tests/index.js
  src/components/ExampleComponent/tests/__snapshots__/index.js.snap
  src/components/FilterPicker/tests/__snapshots__/index.js.snap
  src/components/HelpPopover/tests/__snapshots__/index.js.snap
  src/components/Input/tests/index.js
  src/components/NavBar/CurrentUserMenu/AccountSwitcher/tests/index.js
  src/components/SearchPicker/tests/__snapshots__/index.js.snap
  src/components/TextField/tests/__snapshots__/index.js.snap
  src/components/Token/DismissButton/tests/index.js
  src/components/TokensInput/tests/index.js
  types/index.d.ts
  yarn.lock
Labels: :robot: 4 hrs, :robot: 6 hrs

#1423 feat(Badge): Added Background Color support to Badge
  CHANGELOG.md
  src/components/Badge/Badge.story.js
  src/components/Badge/index.js
Labels: :robot: 0.2 hrs
