Repository optimizely/oui, pull requests merged in 2020-07, with the labels that each got.

#1365 [UXENG-74] Added built-in sorting to tables
  CHANGELOG.md
  src/components/Table/TH/index.js
  src/components/Table/Table.story.js
  src/components/Table/tests/index.js
  types/index.d.ts
Labels: :robot: 2 hrs

#1367 [UXENG-4] Flexbox helper class documentation
  .storybook/config.js
  .storybook/helper_classes/flexbox.story.tsx
  .storybook/helper_classes/flexboxInteractive.tsx
  .storybook/helper_classes/index.scss
  CHANGELOG.md
Labels: :robot: 2 hrs

#1372 feat(Code): Add ability to wrap content
  CHANGELOG.md
  src/components/Code/Code.story.js
  src/components/Code/index.js
  src/components/Code/index.scss
  src/components/Code/tests/index.js
Labels: :robot: 4 hrs, :robot: 6 hrs

#1373 [UXENG-4] Added typography helper class story
  .storybook/helper_classes/flexboxInteractive.tsx
  .storybook/helper_classes/index.scss
  .storybook/helper_classes/typography.story.tsx
  .storybook/helper_classes/typography.tsx
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
Labels: :robot: 4 hrs, :robot: 6 hrs

#1376 feat(SelectDropdown): Add ability for placement
  CHANGELOG.md
  src/components/Code/index.js
  src/components/SelectDropdown/SelectDropdown.story.js
  src/components/SelectDropdown/index.js
  types/index.d.ts
Labels: :robot: 0.1 hrs

#1384 feat(NavBar): Add option for custom footerContent
  CHANGELOG.md
  src/components/NavBar/CurrentUserMenu/index.js
  src/components/NavBar/NavBar.story.js
  src/components/NavBar/index.js
  src/components/NavBar/index.scss
  types/index.d.ts
Labels: :robot: 2 hrs

#1383 [UXENG-86] Added Icon option to buttons
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  src/components/Button/Button.story.js
  src/components/Button/index.js
  src/components/Button/tests/index.js
  types/index.d.ts
Labels: :robot: 4 hrs, :robot: 6 hrs

#1385 [UXENG-109] Fixed console errors for SearchPicker component
  CHANGELOG.md
  src/components/SearchPicker/index.js
  src/components/SearchPicker/tests/__snapshots__/index.js.snap
  src/components/SearchPicker/tests/index.js
  types/index.d.ts
Labels: :robot: 4 hrs, :robot: 6 hrs

#1386 [UXENG-131] Add ability to add icons to button links
  CHANGELOG.md
  data/csswhat/oui.css
  data/csswhat/oui.css.json
  src/components/Button/Button.story.js
  src/components/Button/index.js
  src/components/Link/Link.story.js
  src/oui/partials/layout/_flexbox.scss
Labels: :robot: 1 hrs

#1388 [UXENG-132] Add onclick prop for table rows
  CHANGELOG.md
  src/components/Table/TR/index.js
  src/components/Table/TR/tests/index.js
Labels: :robot: 0.2 hrs

#1387 feat(Tile): Fix button size and remove bg animation
  CHANGELOG.md
  src/components/Button/index.scss
  src/components/Tile/Tile.story.tsx
  src/components/Tile/index.scss
  src/components/Tile/index.tsx
Labels: :robot: 4 hrs, :robot: 8 hrs
